<?php

/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/**
 * File contains class, that implemented database entity `SysUser`
 *
 * PHP version 5
 * @category   Database Model of the Application
 * @author     Eugene A. Kalosha <ekalosha@gmail.com>
 * @copyright  (c) 2004-2010 by SolArt xIT
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU General Public License version 3.0
 * @version    SVN: $Revision: 98 $
 * @link       http://www.solartxit.com/php2
 * @since      File available since Release 3.0
 */

/**
 * Defining Namespace
 *
 * For PHP versions 5.3 and Higher
 */
// namespace Application\DBLayer;

/**
 * This file is Automatically generated by PHP2 Code Generator.
 * Generation date: 2008-12-20, 13:15:04
 *
 * @author   Eugene A. Kalosha <ekalosha@gmail.com>
 */

/**
 * Class realizes database record of entity `SysUser`
 *
 * @author   Eugene A. Kalosha <ekalosha@gmail.com>
 * @version  $Id: sysuser.class.php 98 2009-08-19 17:15:05Z eugene $
 * @access   public
 * @package  Application\DBLayer
 */
class Application_DBLayer_SysUser extends Application_DBLayer_DBTable
{
    /**
     * Current Table Name
     */
    const TABLE_NAME = 'SysUser';

    /**
     * Automaticaly generated property for field 'ID'
     *
     * @var      integer
     * @access   public
     */
    public $ID;

    /**
     * Automaticaly generated property for field 'GroupID'
     *
     * @var      integer
     * @access   public
     */
    public $GroupID;

    /**
     * Automaticaly generated property for field 'Login'
     *
     * @var      string
     * @access   public
     */
    public $Login;

    /**
     * Automaticaly generated property for field 'UserPassword'
     *
     * @var      string
     * @access   public
     */
    public $UserPassword;

    /**
     * Automaticaly generated property for field 'FirstName'
     *
     * @var      string
     * @access   public
     */
    public $FirstName;

    /**
     * Automaticaly generated property for field 'LastName'
     *
     * @var      string
     * @access   public
     */
    public $LastName;

    /**
     * Automaticaly generated property for field 'EMail'
     *
     * @var      string
     * @access   public
     */
    public $EMail;

    /**
     * Automaticaly generated property for field 'RegistrationDate'
     *
     * @var      PHP2_Database_DataType_DateTime
     * @access   public
     */
    public $RegistrationDate;

    /**
     * Automaticaly generated property for field 'Enabled'
     *
     * @var      integer
     * @access   public
     */
    public $Enabled;

    /**
     * Automaticaly generated property for field 'LoginsCount'
     *
     * @var      integer
     * @access   public
     */
    public $LoginsCount;

    /**
     * Automaticaly generated property for field 'LastLogin'
     *
     * @var      integer
     * @access   public
     */
    public $LastLogin;

    /**
     * Automaticaly generated property for field 'LastSecurityUpdateTime'
     *
     * @var      integer
     * @access   public
     */
    public $LastSecurityUpdateTime;

    /**
     * Automaticaly generated property for field 'IsConfirmed'
     *
     * @var      integer
     * @access   public
     */
    public $IsConfirmed;

    /**
     * Automaticaly generated property for field 'ConfirmationCode'
     *
     * @var      string
     * @access   public
     */
    public $ConfirmationCode;

    /**
     * Automaticaly generated property for field 'SecuritySessionID'
     *
     * @var      string
     * @access   public
     */
    public $SecuritySessionID;

    /**
     * Automaticaly generated property for field 'SecuritySessionExpireTime'
     *
     * @var      integer
     * @access   public
     */
    public $SecuritySessionExpireTime;

    /**
     * Automaticaly generated property for field 'CountryID'
     *
     * @var      integer
     * @access   public
     */
    public $CountryID;

    /**
     * Automaticaly generated property for field 'StateID'
     *
     * @var      integer
     * @access   public
     */
    public $StateID;

    /**
     * Automaticaly generated property for field 'CityID'
     *
     * @var      integer
     * @access   public
     */
    public $CityID;

    /**
     * Class constructor
     *
     * @param   integer $pkFieldValue Current record Unique ID
     * @access  public
     */
    public function __construct($pkFieldValue = null)
    {
        $this->_tableName = self::TABLE_NAME;

        // --- Calling Parent Constructor --- //
        parent::__construct($pkFieldValue);
    }

    /**
     * Returns user Id by It's Cookie security Session code
     *
     * @param   string $securitySessionId Security Cookie code
     * @param   string $expireTime
     * @return  integer
     */
    public function getUserIdBySecuritySession($securitySessionId, $expireTime = false)
    {
        $queryAdd = ($expireTime) ? ' AND SecuritySessionExpireTime>=\''.$expireTime.'\'' : '';

        return $this->searchRecord('SecuritySessionID=\''.$securitySessionId.'\''.$queryAdd);
    }

    /**
     * Returns user Id by It's Login
     *
     * @param   string $userLogin
     * @return  integer
     */
    public function getUserIdByLogin($userLogin)
    {
        return $this->searchRecord('Login=\''.$userLogin.'\'');
    }

    /**
     * Returns Paged List of Records for Table
     *
     * @param   integer $pageSize   Recorde per page
     * @param   integer $pageNumber Current page number
     * @param   string  $sortField Sort Field name
     * @param   string  $sortOrder Sort Order
     * @param   array   $searchPattern Search Pattern Structure
     * @return  PHP2_Database_SQLQuery
     * @access  public
     */
    public function getUsersListPaged($pageSize, $pageNumber, $sortField = null, $sortOrder = null, $searchPattern = false)
    {
        $sqlQuery  = 'SELECT u.*, g.GroupName, c.CountryName FROM `SysUser` AS u LEFT JOIN `SysGroup` AS g ON g.ID=u.GroupID ';
        $sqlQuery .= 'LEFT JOIN `Country` AS c ON c.ID=u.CountryID ';
        $sqlQuery .= 'WHERE '.$this->_getSearchPattern($searchPattern);

        return PHP2_Database_SQLQuery::executePagedQuery($sqlQuery, $this->_hConnection, $pageSize, $pageNumber, $sortField, $sortOrder);
    }

    /**
     * Increments logins count for the user
     *
     * @return  PHP2_Database_SQLQuery
     * @access  public
     */
    public function incrementLoginsCount()
    {
        $sqlQuery  = 'UPDATE `SysUser` SET `LoginsCount` = `LoginsCount` + 1';

        return PHP2_Database_SQLQuery::executeQuery($sqlQuery, $this->_hConnection);
    }

}
